### ISSUE TITLE
cannot display help for apt-get

### ISSUE THREAD

**Issue by severak** [ostera/tldr.jsx#75] opened 2016-11-01 23:04 UTC
cannot display help for apt-get command, probably dash brokes index.

**Comment by ostera** [comment] 2016-11-03 07:36
Hi! It's not a bug, it's a feature 😝 

Fortunately, it is accessible but it has to be namespaced with the platform: https://tldr.ostera.io/linux/apt-get

Related to #70 and #60, `tldr.jsx` should know better than this! I'll close this but keep it linked to the other one so it doesn't get lost.

Thanks!

**Closed by ostera** 2016-11-03 07:36 UTC

**Comment by severak** [comment] 2016-11-03 08:31
`apt-get` is not available for platforms other than linux. So it should display even without prefix IMHO.

**Comment by ostera** [comment] 2016-11-03 08:33
Yeah, we agree on that. The two linked issues are directly related to this issue.
